### PR TITLE
Client minor bugfixes

### LINKED ISSUE #153: Delete an item deletes all mapping rules
When an item in an array is deleted with a right click ("supprimer l'item"), then the mapping rules of the other items in the same array are deleted.
Moreover, the attributes are not clickable when this action is done (needs refresh)

### LINKED ISSUE #155: Delete source not working properly
When the (X) is selected to delete a source, the attributes mapped are removed but the source itself is not removed.

### PR DESCRIPTION
**Pull request by Jasopaum**
Fixes #155
Fixes #153
Should fix a bit of #149

### CODE REVIEW

File: client/src/services/selectedNode/actions.tsx [hunk 1]
```diff
@@ -27,65 +27,66 @@ export const updateSelectedSource = (source: {
...
+    name: string;
+    hasOwner: boolean;
+    template: {
+      name: string;
+    };
+    credential: {
+      id: string;
+    };
+  },
+  body: any
```
Comment (simonvadee) [inline client/src/services/selectedNode/actions.tsx]: change to dbSchema or something

File: client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx [hunk 2]
```diff
@@ -268,6 +268,10 @@ const FhirResourceTree = ({ onClickCallback }: Props) => {
     let existingChildrenIds = Object.keys(attributesForResource)
       .filter(key => key.startsWith(pathKey))
       .map(key => key.slice(pathKey.length + 1).split('.')[0]);
+    // Remove duplicates
+    existingChildrenIds = existingChildrenIds.filter(
+      (id, ind) => existingChildrenIds.indexOf(id) === ind
```
Comment (simonvadee) [inline client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx]: use `new Set`

File: client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx [hunk 3]
```diff
@@ -452,9 +456,22 @@ const FhirResourceTree = ({ onClickCallback }: Props) => {
       node.nodeData?.isPrimitive &&
       !node.nodeData?.isArray &&
       Object.keys(attributesForResource).includes(pathString);
-    const hasChildAttributes = Object.keys(attributesForResource).some(el =>
-      el.startsWith(pathString)
-    );
+
+    let hasChildAttributes = false;
+    if (node.id.toString().endsWith('[x]')) {
```
Comment (simonvadee) [inline client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx]: add utility function (isSlice ?)

File: client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx [hunk 4]
```diff
@@ -452,9 +456,22 @@ const FhirResourceTree = ({ onClickCallback }: Props) => {
...
+      // Check if any of the children have child attributes
+      hasChildAttributes = node
+        .childNodes!.map(n => n.id)
+        .some(childName =>
+          Object.keys(attributesForResource).some(el =>
+            el.startsWith(childName.toString())
```
Comment (simonvadee) [inline client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx]: wtf

File: client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx [hunk 5]
```diff
@@ -265,13 +271,14 @@ const FhirResourceTree = ({ onClickCallback }: Props) => {
...
-    // Remove duplicates
-    existingChildrenIds = existingChildrenIds.filter(
-      (id, ind) => existingChildrenIds.indexOf(id) === ind
-    );
+    // We use Set to remove duplicate ids
+    let existingChildrenIds = [
+      ...new Set(
+        Object.keys(attributesForResource)
+          .filter(key => key.startsWith(pathKey))
+          .map(key => key.slice(pathKey.length + 1).split('.')[0])
```
Comment (simonvadee) [inline client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx]: substring
