### PR TITLE
fix: context menu

### LINKED ISSUE #435: Fix pyrog context menu
## Description

Cannot add extension or slice because the context menu automatically closes on click

### Extension
- Choose a random source from dev or staging
- Choose a random resource
- Try to add an extension ==> The second context menu with the choice of extension closes immediately after clicking on "add an extension"

### Profile
- Choose the synthetic source from staging
- Select a Variant resource
- Try to add a slice on the component attribute (the last one on the bottom of the page) ==> The second context menu with the choice of slice closes immediately after clicking on "add a slice"

## Expectation

Possibility to add extension or slices

## Environment

Staging, dev

### PR DESCRIPTION
**Pull request by tevariou**
## Fixes

Fixes #435  by @nriss 

## Description

* Specify popover interaction on Select component to fix the menu disappearing on click

## Tests

* Select menu when adding an extension or a slice should appear

### CODE REVIEW

File: client/src/components/selects/addExtensionSelect.tsx [hunk 1]
```diff
@@ -136,7 +136,8 @@ const AddExtensionSelect = ({
           canEscapeKeyClose: true,
           lazy: true,
           position: Position.RIGHT_TOP,
-          usePortal: true
+          usePortal: true,
+          interactionKind: PopoverInteractionKind.HOVER
```
Comment (Jasopaum) [inline client/src/components/selects/addExtensionSelect.tsx:140]: Won't that display the popover whenever the user hovers onto the fhirResourceTree?

Comment (simonvadee) [reply client/src/components/selects/addExtensionSelect.tsx:140]: I think these props are applied on the popover directly, not to the resourceTree

**Review by simonvadee — APPROVED** [review]
