### PR TITLE
Fix table preview

### LINKED ISSUE #456: Changing resource induce a black screen
## Reproduction

1. Go on osiris synthetic source
2. Change the resource multiple time until seeing the black screen

## Environment

Staging, osiris synthetic

## Additional context

Can be resolved by refreshing the page

### PR DESCRIPTION
**Pull request by Jasopaum**
## Fixes
Fixes #456 for real (?)

### CODE REVIEW

File: client/src/components/mapping/TableViewer/index.tsx [hunk 1]
```diff
@@ -147,7 +132,15 @@ const TableViewer = ({ table }: IProps) => {
             : []
         }
       >
-        {columns}
+        {fields.map((field: string, index: number) => {
+          return (
```
Comment (simonvadee) [inline client/src/components/mapping/TableViewer/index.tsx:136]: skip return statement

**Review by simonvadee — APPROVED** [review]

**Review by nriss — APPROVED** [review]
Thanks 👌
